#color definition
string(ASCII 27 esc)
set(RED          "${esc}[31m")
set(GREEN        "${esc}[32m")
set(YELLOW       "${esc}[33m")
set(BLUE         "${esc}[34m")
set(MAGENTA      "${esc}[35m")
set(CYAN         "${esc}[36m")
set(WHITE        "${esc}[37m")
set(BOLD_RED     "${esc}[1;31m")
set(BOLD_GREEN   "${esc}[1;32m")
set(BOLD_YELLOW  "${esc}[1;33m")
set(BOLD_BLUE    "${esc}[1;34m")
set(BOLD_MAGENTA "${esc}[1;35m")
set(BOLD_CYAN    "${esc}[1;36m")
set(BOLD_WHITE   "${esc}[1;37m")
set(BOLD_COLOR   "${esc}[1m")  
set(END  "${esc}[m")  

