set(CMAKE_SYSTEM_NAME Generic)

# Toolchain
if(CMAKE_SYSTEM_PROCESSOR STREQUAL "arm")
set(COMPILER_PREFIX "arm-none-eabi")
elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "risc-v")
set(COMPILER_PREFIX "riscv-none-elf")
endif()
# find ${COMPILER_PREFIX}-gcc binary
execute_process(
  COMMAND which ${COMPILER_PREFIX}-gcc
  OUTPUT_VARIABLE TOOLCHAIN_GCC_PATH
  OUTPUT_STRIP_TRAILING_WHITESPACE
)
# extract toolchain path
get_filename_component(TOOLCHAIN_PATH ${TOOLCHAIN_GCC_PATH} DIRECTORY)
message(STATUS "${BOLD_GREEN}Toolchain path: ${TOOLCHAIN_PATH}/${COMPILER_PREFIX}-${END}")

# cmake-format: off
find_program(CMAKE_C_COMPILER NAMES ${COMPILER_PREFIX}-gcc HINTS ${TOOLCHAIN_BIN_PATH})
find_program(CMAKE_CXX_COMPILER NAMES ${COMPILER_PREFIX}-g++ HINTS ${TOOLCHAIN_BIN_PATH})
find_program(CMAKE_AR NAMES ${COMPILER_PREFIX}-ar HINTS ${TOOLCHAIN_BIN_PATH})
find_program(CMAKE_RANLIB NAMES ${COMPILER_PREFIX}-ranlib HINTS ${TOOLCHAIN_BIN_PATH})
find_program(CMAKE_LINKER NAMES ${COMPILER_PREFIX}-ld HINTS ${TOOLCHAIN_BIN_PATH})
find_program(CMAKE_ASM_COMPILER NAMES ${COMPILER_PREFIX}-gcc HINTS ${TOOLCHAIN_BIN_PATH})
find_program(CMAKE_OBJCOPY NAMES ${COMPILER_PREFIX}-objcopy HINTS ${TOOLCHAIN_BIN_PATH})
find_program(CMAKE_OBJDUMP NAMES ${COMPILER_PREFIX}-objdump HINTS ${TOOLCHAIN_BIN_PATH})
find_program(CMAKE_SIZE NAMES ${COMPILER_PREFIX}-size HINTS ${TOOLCHAIN_BIN_PATH})

# https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html#cmake-toolchains-7
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

# Define the compiler to be used for C and C++
set(CMAKE_C_COMPILER ${COMPILER_PREFIX}-gcc)
set(CMAKE_CXX_COMPILER ${COMPILER_PREFIX}-g++)

# Define the assembler to be used
set(CMAKE_ASM_COMPILER ${COMPILER_PREFIX}-as)

# Define the tool for archiving libraries
set(CMAKE_AR ${COMPILER_PREFIX}-ar)
set(CMAKE_NM ${COMPILER_PREFIX}-nm)
set(CMAKE_OBJCOPY ${COMPILER_PREFIX}-objcopy)
set(CMAKE_OBJDUMP ${COMPILER_PREFIX}-objdump)
set(CMAKE_RANLIB ${COMPILER_PREFIX}-ranlib)
set(CMAKE_SIZE ${COMPILER_PREFIX}-size)

# Define the linker
set(CMAKE_EXE_LINKER ${COMPILER_PREFIX}-gcc)
